# Generated by Django 4.2.16 on 2024-11-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_saleslog_alter_customers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='halls',
            options={'verbose_name': 'Hall'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Position'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sale'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'verbose_name': 'Session'},
        ),
        migrations.AlterModelOptions(
            name='sessiontypes',
            options={'verbose_name': 'Session Type'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Ticket'},
        ),
    ]
