# Generated by Django 4.2.16 on 2024-12-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customers_options_alter_halls_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedReports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.TextField()),
                ('status', models.IntegerField()),
                ('link', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ExportedReport',
                'db_table': 'exported_reports',
            },
        ),
    ]
