# Generated by Django 4.2.16 on 2024-12-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exportedreports_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportedreports',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
