# Generated by Django 4.2.16 on 2024-12-07 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customers_options_alter_halls_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportedreports',
            old_name='link',
            new_name='excel_filepath',
        ),
        migrations.AddField(
            model_name='exportedreports',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 17, 28, 15, 790932)),
        ),
        migrations.AddField(
            model_name='exportedreports',
            name='word_filepath',
            field=models.TextField(null=True),
        ),
    ]
